# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Model Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo with submodules
      uses: actions/checkout@v2
      with:        
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('ModelTraining/datamodels/requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f ModelTraining/requirements.txt ]; then pip install -r ModelTraining/requirements.txt; fi
        if [ -f ModelTraining/datamodels/requirements.txt ]; then pip install -r ModelTraining/datamodels/requirements.txt; fi
    #- name: set pythonpath
    #  run: |
    #    echo "PYTHONPATH=$PYTHONPATH;./;./ModelTraining/datamodels/" >> $GITHUB_ENV
    # Alternative env method:
    #  source .env_github
    - name: Run model training
      env:
        REPO_PATH: "${{github.workspace}}"
        PYTHONPATH: "${{github.workspace}};${{github.workspace}}/datamodels;${{github.workspace}};${{github.workspace}}/Data"
      run: |
        python -m main_basic
        python -m main_beyond
        python -m main_experiments
